package com.unp.a3.Routing.enums;

public enum ViewKey {
    MAIN,
    HOME,
    SIGNUP_PRODUCT,
    MANAGER_PRODUCTS,
    REGISTER_INPUT_PRODUCT,
    REGISTER_OUTPUT_PRODUCT,
    SIGNUP_EMPLOYEE,
    MANAGER_EMPLOYEE,
    RELATORY
}
